require 'rubygems'
require 'cucumber'
require File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib', 'tlb'))
require 'tlb/cucumber/cucumber_task'

Tlb::Cucumber::CucumberTask.new('foo')

load 'tasks/tlb.rake'
desc "run specs load-balanced(based on environment variables)"
task :bal => ['tlb:start', :foo]

